// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace CubeTower2D
{
public static class GPGSIds
{
        public const string achievement_open_the_hard_mode = "CgkIqMWb58IFEAIQAQ"; // <GPGSID>
        public const string leaderboard_table_of_losing_time_records = "CgkIqMWb58IFEAIQCQ"; // <GPGSID>
        public const string leaderboard_normal_mode_record_table = "CgkIqMWb58IFEAIQBg"; // <GPGSID>
        public const string achievement_i_am_the_creator = "CgkIqMWb58IFEAIQDQ"; // <GPGSID>
        public const string leaderboard_table_of_time_mode_records = "CgkIqMWb58IFEAIQBw"; // <GPGSID>
        public const string achievement_open_the_on_time_mode = "CgkIqMWb58IFEAIQAA"; // <GPGSID>
        public const string achievement_he_is_interested_in_this_game = "CgkIqMWb58IFEAIQBA"; // <GPGSID>
        public const string achievement_open_the_mode_of_creative = "CgkIqMWb58IFEAIQAg"; // <GPGSID>
        public const string leaderboard_table_of_records_for_hard_mode = "CgkIqMWb58IFEAIQCA"; // <GPGSID>
        public const string achievement_the_player_discovered = "CgkIqMWb58IFEAIQAw"; // <GPGSID>
        public const string achievement_am_i_crazy = "CgkIqMWb58IFEAIQDA"; // <GPGSID>
        public const string achievement_game_professional_detected = "CgkIqMWb58IFEAIQBQ"; // <GPGSID>

}
}
